### ISSUE TITLE
OUTDATED

### ISSUE THREAD

**Issue by cescoferraro** [freetronics/PiLeven-tools#2]
sysvinit has been replaced with systemctl

```
pi@raspberrypi:~ $ sudo sh install_pileven.sh
WARNING: Console mechanism not found. You will need to disable the ttyAMA0 conso          le manually.
Installing /usr/local/sbin/set_pin_alt.py...
Done installing PiLeven support. Please reboot before running the Arduino IDE.
```

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=123081

**Comment by projectgus** [comment]
New PiLeven tools update should work correctly with systemd on Raspbian:
http://forum.freetronics.com/viewtopic.php?f=44&t=6561&p=15677#p15677
