### ISSUE TITLE
install script installed but still cant upload arduino sketch

### ISSUE THREAD

**Issue by jesuswithyoyo** [freetronics/PiLeven-tools#4]
i have no errors reported with install on RPi3.
I use Arduino IDE on RPi3
I set Board = Arduino UNO
i set Serial Port = /dev/ttyS99
i use Programmer = AVRISP mkII
then upload sketch *ERROR
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

is this my dumbnerd fault? is this an easy fix?

wiringpi is installed :D 
 +-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5V      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | ALT0 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT0 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 | ALT3 | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | IN   | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+

**Comment by projectgus** [comment]
This sounds like it should work, and the pin modes are set right. 

Do you see the red led (marked L) flicker on the PiLeven when you press the Upload button? How about the TX and RX LEDs?

**Comment by jesuswithyoyo** [comment]
red led D13= flashing all the time
green led RX= will flash once only then error is displayed in ide
yellow led TX= will light up if i have a arduino shield on pileven
blue led P= is cool :D

**Comment by projectgus** [comment]
Sorry for the really slow reply, I'm on holidays at the moment.

Does the red LED flicker at all when you press upload, or does the pace of the blinking stay unchanged? If it doesn't flicker briefly then the automotic reset into the bootloader may not be working for some reason. To verify this diagnosis, try pressing "reset" on the PiLeven at the same time you press "upload" in Arduino. 

Another thing to try: If you go to arduino preferences and select Verbose Upload, can you please copy and paste the verbose output that appears when you press the Upload button?

**Comment by jesuswithyoyo** [comment]
Red LED has no flicker and it's pulse is unchanging.  
Pressing reset button on upload has no effect on Red Led pulse.
Pressing reset button will make the Green LED flash once but still have error.

I think you are correct in saying "the automotic reset into the bootloader may not be working for some reason."
I do not know how to fix this. I will start reading random web searches on this.

I can upload to other Arduino boards from the RPi3.

Below is the verbose output for the failed upload. (Arduino IDE running as root)

---

/usr/share/arduino/hardware/tools/avrdude -C/usr/share/arduino/hardware/tools/avrdude.conf -v -v -v -v -patmega328p -carduino -P/dev/ttyS99 -b115200 -D -Uflash:w:/tmp/build6392987588356421955.tmp/Sweep.cpp.hex:i 

avrdude: Version 6.1, compiled on Jul  7 2015 at 10:29:47
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

```
     System wide configuration file is "/usr/share/arduino/hardware/tools/avrdude.conf"
     User configuration file is "/root/.avrduderc"
     User configuration file does not exist or is not a regular file, skipping

     Using Port                    : /dev/ttyS99
     Using Programmer              : arduino
     Overriding Baud Rate          : 115200
```

avrdude: Send: 0 [30]   [20] 
avrdude: Send: 0 [30]   [20] 
avrdude: Send: 0 [30]   [20] 
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

---

Projectgus your guidance is very much appreciated. 
=JWY

**Comment by projectgus** [comment]
Sorry for the slow reply. This sounds like it's probably a hardware issue, if you drop us a line at support@freetronics.com then we will sort you out.

Angus
